# -*- coding: utf-8 -*-
"""DCS_central tendency case study Wine Quality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UHzpgZLsrRDJoBnDZpPDJNGNQwrPLVBI
"""

import pandas as pd
import numpy as np

import seaborn as sns

data= pd.read_csv('/content/Employee Dataset.csv')
data.head(5)

data.shape

data.index

data.columns

data.info()

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
sns.scatterplot(data=data,x='healthy_eating',y='active_lifestyle',color='red',alpha=0.5)
plt.title('PLot of Healthy eating Vs Active lifestyle')

plt.figure(figsize=(10,5))
sns.countplot(data=data,x='groups',edgecolor='linen',alpha=0.7)
plt.title('Count of groups')
plt.show()

plt.figure(figsize=(11,6))
sns.histplot(data=data,x='salary',edgecolor='linen',alpha=0.7)
plt.title('Salary plot')
plt.show()